-- 131_narrow_india_universe_to_nifty500.sql
-------------------------------------------------------------------
-- Avdhoot (P6, 2026-09-24): "Decrease the scope of Indian Stocks to
-- only NIFTY 500; lets not have all the 2500 stocks (remove the extra
-- above 500). This will free up supabase space, focus more on core
-- stocks, and also help us build this MVP very well."
--
-- Hard-deletes every India equity NOT in the current Nifty 500 index
-- (Avdhoot's explicit choice over soft-deactivating them -- this
-- actually frees up space, at the cost of being irreversible). The
-- keep-list below is this project's own `nifty500_master.csv` (already
-- in this repo, verified against NSE's own ind_nifty500list.csv --
-- more reliable than a fresh web fetch, which had one stale/renamed
-- symbol at the time this migration was written: HEGAM vs the
-- correct HEG, and a spurious DUMMYHEG placeholder row),
-- matched against `assets.ticker` for market='india', asset_type='equity'
-- (assets.ticker stores the bare NSE symbol, e.g. 'RELIANCE' -- same
-- convention 104_weekly_universe_sync_india.py already relies on).
--
-- IMPORTANT -- READ BEFORE RUNNING:
--   1. This is IRREVERSIBLE. It deletes price history, fundamentals,
--      scores, and every other row tied to the removed stocks, from
--      EVERY table that references assets(asset_id) -- discovered
--      automatically via Postgres's own foreign-key catalog (step 2
--      below), so this doesn't rely on a hand-maintained table list
--      that could miss one added by a later migration.
--   2. Take a backup first if you're not fully sure (Supabase Project
--      Settings -> Database -> Backups, or just export the `assets`
--      table) -- there is no undo once this commits.
--   3. This whole script runs inside one transaction (BEGIN/COMMIT at
--      the very top/bottom) -- if anything looks wrong from the
--      NOTICE lines Supabase prints while it runs, you can stop
--      before the COMMIT line and it rolls back cleanly. If you paste
--      the whole file at once into Supabase's SQL Editor, it commits
--      automatically at the end, same as any other migration in this
--      project -- reread the NOTICE output afterwards instead.
--   4. Two tables are NOT foreign-key-enforced and are deliberately
--      left untouched: `saved_comparisons.asset_ids` (a plain integer
--      array behind old share links) and any JSON blob elsewhere that
--      might mention a removed asset_id. Worst case, an old shared
--      comparison link for a removed stock stops resolving -- not a
--      data-integrity problem, just a dead link.
--   5. After this runs, ALSO update 104_weekly_universe_sync_india.py
--      (done in this same session, see BUILD_LOG) so future weekly
--      syncs keep sourcing from the Nifty 500 list, not NSE's full
--      ~2500-stock mainboard list -- otherwise the next weekly sync
--      would just re-add everything this script removes.
--
-- Safe to re-run: if the extra stocks are already gone, step 2/3
-- simply delete 0 rows.
-------------------------------------------------------------------

begin;

create temporary table nifty500_keep (ticker text primary key) on commit drop;
insert into nifty500_keep (ticker) values
  ('360ONE'),
  ('3MINDIA'),
  ('AADHARHFC'),
  ('AARTIIND'),
  ('AAVAS'),
  ('ABB'),
  ('ABBOTINDIA'),
  ('ABCAPITAL'),
  ('ABDL'),
  ('ABFRL'),
  ('ABLBL'),
  ('ABREL'),
  ('ABSLAMC'),
  ('ACC'),
  ('ACE'),
  ('ACMESOLAR'),
  ('ACUTAAS'),
  ('ADANIENSOL'),
  ('ADANIENT'),
  ('ADANIGREEN'),
  ('ADANIPORTS'),
  ('ADANIPOWER'),
  ('AEGISLOG'),
  ('AEGISVOPAK'),
  ('AFCONS'),
  ('AFFLE'),
  ('AIAENG'),
  ('AIIL'),
  ('AJANTPHARM'),
  ('ALKEM'),
  ('AMBER'),
  ('AMBUJACEM'),
  ('ANANDRATHI'),
  ('ANANTRAJ'),
  ('ANGELONE'),
  ('ANTHEM'),
  ('ANURAS'),
  ('APARINDS'),
  ('APLAPOLLO'),
  ('APOLLOHOSP'),
  ('APOLLOTYRE'),
  ('APTUS'),
  ('ARE&M'),
  ('ASAHIINDIA'),
  ('ASHOKLEY'),
  ('ASIANPAINT'),
  ('ASTERDM'),
  ('ASTRAL'),
  ('ATGL'),
  ('ATHERENERG'),
  ('ATUL'),
  ('AUBANK'),
  ('AUROPHARMA'),
  ('AWL'),
  ('AXISBANK'),
  ('BAJAJ-AUTO'),
  ('BAJAJFINSV'),
  ('BAJAJHFL'),
  ('BAJAJHLDNG'),
  ('BAJFINANCE'),
  ('BALKRISIND'),
  ('BALRAMCHIN'),
  ('BANDHANBNK'),
  ('BANKBARODA'),
  ('BANKINDIA'),
  ('BATAINDIA'),
  ('BAYERCROP'),
  ('BBTC'),
  ('BDL'),
  ('BEL'),
  ('BELRISE'),
  ('BEML'),
  ('BERGEPAINT'),
  ('BHARATFORG'),
  ('BHARTIARTL'),
  ('BHARTIHEXA'),
  ('BHEL'),
  ('BIKAJI'),
  ('BIOCON'),
  ('BLS'),
  ('BLUEDART'),
  ('BLUEJET'),
  ('BLUESTARCO'),
  ('BOSCHLTD'),
  ('BPCL'),
  ('BRIGADE'),
  ('BRITANNIA'),
  ('BSE'),
  ('BSOFT'),
  ('CAMS'),
  ('CANBK'),
  ('CANFINHOME'),
  ('CANHLIFE'),
  ('CAPLIPOINT'),
  ('CARBORUNIV'),
  ('CARTRADE'),
  ('CASTROLIND'),
  ('CCL'),
  ('CDSL'),
  ('CEATLTD'),
  ('CEMPRO'),
  ('CENTRALBK'),
  ('CESC'),
  ('CGCL'),
  ('CGPOWER'),
  ('CHALET'),
  ('CHAMBLFERT'),
  ('CHENNPETRO'),
  ('CHOICEIN'),
  ('CHOLAFIN'),
  ('CHOLAHLDNG'),
  ('CIEINDIA'),
  ('CIPLA'),
  ('CLEAN'),
  ('COALINDIA'),
  ('COCHINSHIP'),
  ('COFORGE'),
  ('COHANCE'),
  ('COLPAL'),
  ('CONCOR'),
  ('CONCORDBIO'),
  ('COROMANDEL'),
  ('CPPLUS'),
  ('CRAFTSMAN'),
  ('CREDITACC'),
  ('CRISIL'),
  ('CROMPTON'),
  ('CUB'),
  ('CUMMINSIND'),
  ('CYIENT'),
  ('DABUR'),
  ('DALBHARAT'),
  ('DATAPATTNS'),
  ('DCMSHRIRAM'),
  ('DEEPAKFERT'),
  ('DEEPAKNTR'),
  ('DELHIVERY'),
  ('DEVYANI'),
  ('DIVISLAB'),
  ('DIXON'),
  ('DLF'),
  ('DMART'),
  ('DOMS'),
  ('DRREDDY'),
  ('ECLERX'),
  ('EICHERMOT'),
  ('EIDPARRY'),
  ('EIHOTEL'),
  ('ELECON'),
  ('ELGIEQUIP'),
  ('EMAMILTD'),
  ('EMCURE'),
  ('EMMVEE'),
  ('ENDURANCE'),
  ('ENGINERSIN'),
  ('ENRIN'),
  ('ERIS'),
  ('ESCORTS'),
  ('ETERNAL'),
  ('EXIDEIND'),
  ('FACT'),
  ('FEDERALBNK'),
  ('FINCABLES'),
  ('FIRSTCRY'),
  ('FIVESTAR'),
  ('FLUOROCHEM'),
  ('FORCEMOT'),
  ('FORTIS'),
  ('FSL'),
  ('GABRIEL'),
  ('GAIL'),
  ('GALLANTT'),
  ('GESHIP'),
  ('GICRE'),
  ('GILLETTE'),
  ('GLAND'),
  ('GLAXO'),
  ('GLENMARK'),
  ('GMDCLTD'),
  ('GMRAIRPORT'),
  ('GODFRYPHLP'),
  ('GODIGIT'),
  ('GODREJCP'),
  ('GODREJIND'),
  ('GODREJPROP'),
  ('GPIL'),
  ('GRANULES'),
  ('GRAPHITE'),
  ('GRASIM'),
  ('GRAVITA'),
  ('GROWW'),
  ('GRSE'),
  ('GVT&D'),
  ('HAL'),
  ('HAVELLS'),
  ('HBLENGINE'),
  ('HCLTECH'),
  ('HDBFS'),
  ('HDFCAMC'),
  ('HDFCBANK'),
  ('HDFCLIFE'),
  ('HEG'),
  ('HEROMOTOCO'),
  ('HEXT'),
  ('HFCL'),
  ('HINDALCO'),
  ('HINDCOPPER'),
  ('HINDPETRO'),
  ('HINDUNILVR'),
  ('HINDZINC'),
  ('HOMEFIRST'),
  ('HONASA'),
  ('HONAUT'),
  ('HSCL'),
  ('HUDCO'),
  ('HYUNDAI'),
  ('ICICIAMC'),
  ('ICICIBANK'),
  ('ICICIGI'),
  ('ICICIPRULI'),
  ('IDBI'),
  ('IDEA'),
  ('IDFCFIRSTB'),
  ('IEX'),
  ('IFCI'),
  ('IGIL'),
  ('IGL'),
  ('IIFL'),
  ('IKS'),
  ('INDGN'),
  ('INDHOTEL'),
  ('INDIACEM'),
  ('INDIAMART'),
  ('INDIANB'),
  ('INDIGO'),
  ('INDUSINDBK'),
  ('INDUSTOWER'),
  ('INFY'),
  ('INOXWIND'),
  ('INTELLECT'),
  ('IOB'),
  ('IOC'),
  ('IPCALAB'),
  ('IRB'),
  ('IRCON'),
  ('IRCTC'),
  ('IREDA'),
  ('IRFC'),
  ('ITC'),
  ('ITCHOTELS'),
  ('ITI'),
  ('J&KBANK'),
  ('JAINREC'),
  ('JBMA'),
  ('JINDALSAW'),
  ('JINDALSTEL'),
  ('JIOFIN'),
  ('JKCEMENT'),
  ('JKTYRE'),
  ('JMFINANCIL'),
  ('JPPOWER'),
  ('JSL'),
  ('JSWCEMENT'),
  ('JSWDULUX'),
  ('JSWENERGY'),
  ('JSWINFRA'),
  ('JSWSTEEL'),
  ('JUBLFOOD'),
  ('JUBLINGREA'),
  ('JUBLPHARMA'),
  ('JWL'),
  ('JYOTICNC'),
  ('KAJARIACER'),
  ('KALYANKJIL'),
  ('KARURVYSYA'),
  ('KAYNES'),
  ('KEC'),
  ('KEI'),
  ('KFINTECH'),
  ('KIMS'),
  ('KIRLOSENG'),
  ('KOTAKBANK'),
  ('KPIL'),
  ('KPITTECH'),
  ('KPRMILL'),
  ('LALPATHLAB'),
  ('LATENTVIEW'),
  ('LAURUSLABS'),
  ('LEMONTREE'),
  ('LENSKART'),
  ('LGEINDIA'),
  ('LICHSGFIN'),
  ('LICI'),
  ('LINDEINDIA'),
  ('LLOYDSME'),
  ('LODHA'),
  ('LT'),
  ('LTF'),
  ('LTFOODS'),
  ('LTM'),
  ('LTTS'),
  ('LUPIN'),
  ('M&M'),
  ('M&MFIN'),
  ('MAHABANK'),
  ('MANAPPURAM'),
  ('MANKIND'),
  ('MAPMYINDIA'),
  ('MARICO'),
  ('MARUTI'),
  ('MAXHEALTH'),
  ('MAZDOCK'),
  ('MCX'),
  ('MEDANTA'),
  ('MEESHO'),
  ('MFSL'),
  ('MGL'),
  ('MINDACORP'),
  ('MMTC'),
  ('MOTHERSON'),
  ('MOTILALOFS'),
  ('MPHASIS'),
  ('MRF'),
  ('MRPL'),
  ('MSUMI'),
  ('MUTHOOTFIN'),
  ('NAM-INDIA'),
  ('NATCOPHARM'),
  ('NATIONALUM'),
  ('NAUKRI'),
  ('NAVA'),
  ('NAVINFLUOR'),
  ('NBCC'),
  ('NCC'),
  ('NESTLEIND'),
  ('NETWEB'),
  ('NEULANDLAB'),
  ('NEWGEN'),
  ('NH'),
  ('NHPC'),
  ('NIACL'),
  ('NIVABUPA'),
  ('NLCINDIA'),
  ('NMDC'),
  ('NSLNISP'),
  ('NTPC'),
  ('NTPCGREEN'),
  ('NUVAMA'),
  ('NUVOCO'),
  ('NYKAA'),
  ('OBEROIRLTY'),
  ('OFSS'),
  ('OIL'),
  ('OLAELEC'),
  ('OLECTRA'),
  ('ONESOURCE'),
  ('ONGC'),
  ('PAGEIND'),
  ('PARADEEP'),
  ('PATANJALI'),
  ('PAYTM'),
  ('PCBL'),
  ('PERSISTENT'),
  ('PETRONET'),
  ('PFC'),
  ('PFIZER'),
  ('PFOCUS'),
  ('PGEL'),
  ('PHOENIXLTD'),
  ('PIDILITIND'),
  ('PIIND'),
  ('PINELABS'),
  ('PIRAMALFIN'),
  ('PNB'),
  ('PNBHOUSING'),
  ('POLICYBZR'),
  ('POLYCAB'),
  ('POLYMED'),
  ('POONAWALLA'),
  ('POWERGRID'),
  ('POWERINDIA'),
  ('PPLPHARMA'),
  ('PREMIERENE'),
  ('PRESTIGE'),
  ('PTCIL'),
  ('PVRINOX'),
  ('PWL'),
  ('RADICO'),
  ('RAILTEL'),
  ('RAINBOW'),
  ('RAMCOCEM'),
  ('RBLBANK'),
  ('RECLTD'),
  ('REDINGTON'),
  ('RELIANCE'),
  ('RHIM'),
  ('RITES'),
  ('RKFORGE'),
  ('RPOWER'),
  ('RRKABEL'),
  ('RVNL'),
  ('SAGILITY'),
  ('SAIL'),
  ('SAILIFE'),
  ('SAMMAANCAP'),
  ('SAPPHIRE'),
  ('SARDAEN'),
  ('SAREGAMA'),
  ('SBFC'),
  ('SBICARD'),
  ('SBILIFE'),
  ('SBIN'),
  ('SCHAEFFLER'),
  ('SCHNEIDER'),
  ('SCI'),
  ('SHREECEM'),
  ('SHRIRAMFIN'),
  ('SHYAMMETL'),
  ('SIEMENS'),
  ('SIGNATURE'),
  ('SJVN'),
  ('SOBHA'),
  ('SOLARINDS'),
  ('SONACOMS'),
  ('SONATSOFTW'),
  ('SPLPETRO'),
  ('SRF'),
  ('STARHEALTH'),
  ('SUMICHEM'),
  ('SUNDARMFIN'),
  ('SUNPHARMA'),
  ('SUNTV'),
  ('SUPREMEIND'),
  ('SUZLON'),
  ('SWANCORP'),
  ('SWIGGY'),
  ('SYNGENE'),
  ('SYRMA'),
  ('TARIL'),
  ('TATACAP'),
  ('TATACHEM'),
  ('TATACOMM'),
  ('TATACONSUM'),
  ('TATAELXSI'),
  ('TATAINVEST'),
  ('TATAPOWER'),
  ('TATASTEEL'),
  ('TATATECH'),
  ('TBOTEK'),
  ('TCS'),
  ('TECHM'),
  ('TECHNOE'),
  ('TEGA'),
  ('TEJASNET'),
  ('TENNIND'),
  ('THELEELA'),
  ('THERMAX'),
  ('TIINDIA'),
  ('TIMKEN'),
  ('TITAGARH'),
  ('TITAN'),
  ('TMCV'),
  ('TMPV'),
  ('TORNTPHARM'),
  ('TORNTPOWER'),
  ('TRAVELFOOD'),
  ('TRENT'),
  ('TRIDENT'),
  ('TRITURBINE'),
  ('TTML'),
  ('TVSMOTOR'),
  ('UBL'),
  ('UCOBANK'),
  ('ULTRACEMCO'),
  ('UNIONBANK'),
  ('UNITDSPR'),
  ('UNOMINDA'),
  ('UPL'),
  ('URBANCO'),
  ('USHAMART'),
  ('UTIAMC'),
  ('VBL'),
  ('VEDL'),
  ('VIJAYA'),
  ('VMM'),
  ('VOLTAS'),
  ('VTL'),
  ('WAAREEENER'),
  ('WELCORP'),
  ('WELSPUNLIV'),
  ('WHIRLPOOL'),
  ('WIPRO'),
  ('WOCKPHARMA'),
  ('YESBANK'),
  ('ZEEL'),
  ('ZENSARTECH'),
  ('ZENTEC'),
  ('ZFCVINDIA'),
  ('ZYDUSLIFE'),
  ('ZYDUSWELL');

create temporary table assets_to_remove (asset_id integer primary key) on commit drop;
insert into assets_to_remove (asset_id)
select asset_id from assets
where market = 'india'
  and asset_type = 'equity'
  and ticker not in (select ticker from nifty500_keep);

-- Sanity check: how many stocks are about to be removed vs kept.
-- Expect "to_remove" to be roughly (current India equity count - ~500)
-- and "to_keep" to be close to 500 -- if these numbers look wrong,
-- stop here (don't run the rest of the file) and flag it instead of
-- proceeding.
select
  (select count(*) from assets_to_remove) as to_remove,
  (select count(*) from assets where market = 'india' and asset_type = 'equity') - (select count(*) from assets_to_remove) as to_keep;

-- Step 2: for every table with a foreign key pointing at
-- assets(asset_id) -- discovered from Postgres's own catalogs, not a
-- hand-typed list -- delete any row belonging to a stock we're
-- removing. Handles `peers.asset_id` AND `peers.peer_asset_id`
-- separately since both are real FKs to assets(asset_id).
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select
      tc.table_schema,
      tc.table_name,
      kcu.column_name,
      tc.constraint_name
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on tc.constraint_name = kcu.constraint_name and tc.table_schema = kcu.table_schema
    join information_schema.constraint_column_usage ccu
      on tc.constraint_name = ccu.constraint_name and tc.table_schema = ccu.table_schema
    where tc.constraint_type = 'FOREIGN KEY'
      and ccu.table_schema = 'public'
      and ccu.table_name = 'assets'
      and ccu.column_name = 'asset_id'
      and tc.table_name <> 'assets'
  loop
    execute format(
      'delete from %I.%I where %I in (select asset_id from assets_to_remove)',
      r.table_schema, r.table_name, r.column_name
    );
    get diagnostics n = row_count;
    raise notice 'Cleared % row(s) from %.% (column %, constraint %)', n, r.table_schema, r.table_name, r.column_name, r.constraint_name;
  end loop;
end $$;

-- Step 3: finally remove the assets themselves.
delete from assets where asset_id in (select asset_id from assets_to_remove);

-- Final report -- should read 500 for India equities.
select count(*) as remaining_india_equities from assets where market = 'india' and asset_type = 'equity';

commit;
