-- 41_add_ai_analysis_column.sql
-- -------------------------------------------------------------------
-- Session pivot: instead of only showing raw DRHP-parsed text, IPO
-- pages now also carry an AI-authored, richly-structured analysis
-- (styled after Avdhoot's own hand-made decks, e.g. the Zepto one).
-- This lives in its own jsonb column, separate from the DRHP fields
-- added in 36_add_drhp_columns.sql, so the two data sources never mix:
--   - business_summary / industry_summary / etc. = mechanically
--     parsed straight out of the DRHP PDF text (36_add_drhp_columns.sql)
--   - ai_analysis = a structured write-up either generated by Claude
--     from an uploaded analysis deck, or (for sections the deck didn't
--     cover) an explicitly-flagged illustrative placeholder
--
-- Shape stored in ai_analysis (each section carries its own
-- is_placeholder flag so the frontend can watermark it):
-- {
--   "company_snapshot":  {"content": "...", "is_placeholder": false},
--   "business_model":    {"content": "...", "is_placeholder": false},
--   "market_landscape":  {"content": "...", "is_placeholder": false},
--   "financials": {
--     "is_placeholder": true,
--     "years": ["FY23","FY24","FY25"],
--     "revenue_cr": [120, 340, 610],
--     "profit_loss_cr": [-80, -140, -95],
--     "note": "..."
--   },
--   "strengths": {"items": ["...", "..."], "is_placeholder": false},
--   "risks":     {"items": ["...", "..."], "is_placeholder": false},
--   "verdict":   {"content": "...", "rating": "Cautious Watch", "is_placeholder": false}
-- }
-- -------------------------------------------------------------------

ALTER TABLE ipo_assessments
  ADD COLUMN IF NOT EXISTS ai_analysis jsonb,
  ADD COLUMN IF NOT EXISTS ai_analysis_updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS ai_analysis_source_filename text;
